# Generated by Django 2.2.3 on 2019-09-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Name', models.CharField(max_length=25)),
                ('Service_Owner', models.CharField(max_length=25)),
                ('Idea_Date', models.CharField(max_length=25)),
                ('Use_Case', models.TextField(max_length=250)),
                ('Automation_Status', models.CharField(max_length=250)),
            ],
        ),
    ]
