# Generated by Django 2.2.3 on 2019-09-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_automation_opurtunity_charter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='Opurtunity_charter',
        ),
        migrations.AddField(
            model_name='automation',
            name='Opportunity_charter',
            field=models.FileField(default='', upload_to='Opportunity_charter'),
            preserve_default=False,
        ),
    ]
