# Generated by Django 2.2.3 on 2019-09-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_auto_20190914_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='Opportunity_charter',
            field=models.FileField(blank=True, upload_to='Opportunity_charter'),
        ),
    ]
